name: Actividad 6 - Automatizacion con Github Actions

on:
  workflow_dispatch:
    inputs:
      nombre:
        description: "Introduce tus nombres y apellidos"
        required: true
        default: ""
        type: string

jobs:
  muestra-nombre:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar el nombre introducido
        run: |
          echo "Tu nombre es: ${{ github.event.inputs.nombre}}"

